Update versioning in create-release workflow

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -48,7 +48,25 @@ jobs:
             --exclude "dist" \
             ./ "dist/${PLUGIN_SLUG}/"
 
-      
+      - name: Set version in plugin info comment
+        id: ver
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          NEW_VERSION="1.3.${{ github.run_number }}"
+          FILE="dist/${THEME_SLUG}/mtg-decklist-block.php"
+
+          if [ ! -f "$FILE" ]; then
+            echo "Missing $FILE" >&2
+            exit 1
+          fi
+
+          # Replace the first match
+          # sed -i -E "s/^Version:[[:space:]]*.*/Version: ${NEW_VERSION}/" "$FILE"
+          sed -i -E "s/^([[:space:]]*\*?[[:space:]]*Version:[[:space:]]*).*/\1${NEW_VERSION}/" "$FILE"
+
+          echo "version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
 
       - name: Package zip
         shell: bash
@@ -65,10 +83,10 @@ jobs:
         uses: softprops/action-gh-release@v2
         # if: github.ref_type == 'tag'
         with:
-          name: "v1.2.${{ github.run_number }}"
+          name: "v1.3.${{ github.run_number }}"
           #name: "v${{ steps.theme.outputs.version }}"
           #tag_name: "v${{ steps.theme.outputs.version }}"
-          tag_name: "v1.0.${{ github.run_number }}"
+          tag_name: "v1.3.${{ github.run_number }}"
           make_latest: true
           files: dist/${{ env.PLUGIN_SLUG }}.zip
           #generate_release_notes: true
@@ -88,4 +106,4 @@ jobs:
           sed --version || true
           ls -la
           ls -la dist/${PLUGIN_SLUG} || true
-          head -n 20 dist/${PLUGIN_SLUG}/mtg-decklist-block.php || true
+          head -n 10 dist/${PLUGIN_SLUG}/mtg-decklist-block.php || true
